sudo: required
dist: trusty

language: node_js
node_js: 6

cache:
  yarn: true

branches:
  only:
    - develop

addons:
  apt:
    packages:
    - icnsutils
    - graphicsmagick
    - xz-utils
    - gcc-multilib
    - g++-multilib

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl https://install.meteor.com/ | sh
  - npm install -g meteor-build-client

script:
  - npm run ci

notifications:
  email:
    - EMAIL
  webhooks:
    urls:
      - YOUR_WEBHOOK_URL
    on_success: change  # options: [always|never|change] default: always
    on_failure: always
    on_start: never
